// src/components/Sponsors.tsx
export const Sponsors: React.FC<{
  tier: number
  sponsors: {
    name?: string
    login: string
    bio?: string
    description?: string
    avatarUrl?: string
  }[]
}> = ({ tier, sponsors }) => {
  return (
    <>
      <div className="group">
        <div className="group-title">${tier} / month</div>
        <div className="group-body">
          {sponsors.map((sponsor) => {
            const bio = sponsor.bio || sponsor.description

            return (
              <div className="group-item" key={sponsor.login}>
                {sponsor.avatarUrl && (
                  <span className="sponsor-avatar">
                    <img src={sponsor.avatarUrl} height="60" width="60" />
                  </span>
                )}
                <div>
                  <a href={`https://github.com/${sponsor.login}`}>
                    {sponsor.name || sponsor.login}
                    {sponsor.name && (
                      <span className="sponsor-login">({sponsor.login})</span>
                    )}
                  </a>
                  {bio && <div className="sponsor-description">{bio}</div>}
                </div>
              </div>
            )
          })}
        </div>
      </div>
      <style scoped>{`.group {
  margin-top: 50px;
}

.group-title {
  font-size: 1.4rem;
  margin-bottom: 10px;
}

.sponsor-login {
  color: #999;
}

.group-body {
  border: 1px solid var(--border-color);
}

.group-item {
  padding: 10px;
  display: flex;
  align-items: center;
}

.group-item + .group-item {
  border-top: 1px solid var(--border-color);
}

.sponsor-avatar {
  margin-right: 12px;
  flex-shrink: 0;
}

.sponsor-description {
  color: var(--secondary-fg);
  font-size: 0.85rem;
}`}</style>
    </>
  )
}

// src/components/Sponsors.vue
<script setup lang="ts">
defineProps({
  tier: null,
  sponsors: null,
})

const normalizeNewLine = (v: string) => v.replace(/\r\n/g, '\n')
</script>

<template>
  <div class="group">
    <div class="group-title">${{ tier }} / month</div>
    <div class="group-body">
      <div class="group-item" v-for="sponsor in sponsors" :key="sponsor.login">
        <span v-if="sponsor.avatarUrl" class="sponsor-avatar">
          <img :src="sponsor.avatarUrl" height="60" width="60" />
        </span>
        <div>
          <a :href="`https://github.com/${sponsor.login}`">
            {{ sponsor.name || sponsor.login }}
            <span v-if="sponsor.name" class="sponsor-login"
              >({{ sponsor.login }})</span
            >
          </a>
          <div
            v-if="sponsor.bio || sponsor.description"
            class="sponsor-description"
          >
            {{ normalizeNewLine(sponsor.bio || sponsor.description) }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.group {
  margin-top: 50px;
}
.group-title {
  font-size: 1.4rem;
  margin-bottom: 10px;
}
.sponsor-login {
  color: #999;
}
.group-body {
  border: 1px solid var(--border-color);
}
.group-item {
  padding: 10px;
  display: flex;
  align-items: center;
}
.group-item + .group-item {
  border-top: 1px solid var(--border-color);
}
.sponsor-avatar {
  margin-right: 12px;
  flex-shrink: 0;
}
.sponsor-description {
  color: var(--secondary-fg);
  font-size: 0.85rem;
}
</style>
