// src/layouts/default.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useHead } from 'saber/app'
import { siteConfig } from 'saber/config'
import Nav from '$src/components/Nav.vue'

const { title, description } = defineProps({
  title: String,
  description: String,
})

const getDesc = (str = '') => str.replace(/<[^>]*>/g, '').slice(0, 100) + '...'

useHead({
  title: computed(() => title),
  meta: computed(() => {
    const desc = getDesc(description)
    return [
      {
        name: 'description',
        content: desc,
      },
      {
        name: 'twitter:description',
        content: desc,
      },
      {
        name: 'twitter:card',
        content: 'summary',
      },
      {
        name: 'twitter:site',
        content: siteConfig.twitter,
      },
    ]
  }),
})
</script>

<template>
  <div class="app">
    <Nav />
    <div class="container">
      <main>
        <div class="page-content"><slot></slot></div>
      </main>
    </div>
  </div>
</template>

// src/layouts/default.tsx
import Head from 'next/head'
import siteConfig from '$siteConfig'
import { Nav } from '../components/Nav'

export default function ({
  children,
  title,
  description,
}: {
  children: React.ReactNode
  title?: string
  description?: string
}) {
  return (
    <>
      <Head>
        {title && <title>{title}</title>}
        {title && <meta name="twitter:title" />}
        {description && <meta name="description" content={description} />}
        {description && (
          <meta name="twitter:description" content={description} />
        )}
        <meta name="twitter:card" content="summary" />
        {siteConfig.twitter && (
          <meta name="twiter:site" content={siteConfig.twitter} />
        )}
      </Head>
      <div className="app">
        <Nav />
        <div className="container">
          <main>
            <div className="page-content">{children}</div>
          </main>
        </div>
      </div>
    </>
  )
}
