// layouts/home.vue
<template>
  <default-layout :page="page">
    <slot></slot>
    <section class="section">
      <div class="section-title">Blog Posts</div>
      <div class="posts">
        <div class="box post" v-for="post in page.posts" :key="post.permalink">
          <a class="post-title" :href="post.permalink">
            <h2>{{ post.title }}</h2>
          </a>
        </div>
      </div>
    </section>
  </default-layout>
</template>

<script>
import Vue from 'vue'
import DefaultLayout from './default.vue'

export default Vue.extend({
  components: {
    DefaultLayout
  },

  props: ['page']
})
</script>

<style scoped>
.post-title h2 {
  font-size: 1rem;
}
</style>

// src/layouts/home.tsx
import pages from '$pages'
import Link from 'next/link'
import DefaultLayout from './default'
import siteConfig from '$siteConfig'

export default function ({ children }) {
  return (
    <>
      <DefaultLayout title={siteConfig.title}>
        {children}
        <section className="section">
          <div className="section-title">Blog Posts</div>
          <div className="posts">
            {pages
              .filter((page) => page.layout === 'post')
              .map((page) => {
                return (
                  <div key={page.slug} className="box post">
                    <Link href={page.permalink}>
                      <a className="post-title">
                        <h2>{page.title}</h2>
                      </a>
                    </Link>
                  </div>
                )
              })}
          </div>
        </section>
      </DefaultLayout>
      <style jsx>
        {`
          .post-title h2 {
            font-size: 1rem;
          }
        `}
      </style>
    </>
  )
}
