// src/layouts/page.tsx
import React from 'react'
import siteConfig from '$siteConfig'
import DefaultLayout from './default'

export default function ({ frontmatter, children }) {
  const isPost = frontmatter.layout === 'post'
  const commentsSection = React.useRef<HTMLDivElement | null>(null)

  const initComments = () => {
    if (!commentsSection.current || !isPost) return

    const attrs = {
      repo: 'egoist/website',
      'issue-term': 'pathname',
      label: 'comment',
      theme: 'preferred-color-scheme',
      crossorigin: 'anonymous',
    }
    const script = document.createElement('script')
    script.src = `https://utteranc.es/client.js`
    script.async = true
    for (const key of Object.keys(attrs)) {
      script.setAttribute(key, attrs[key])
    }
    commentsSection.current.append(script)
  }

  React.useEffect(() => {
    initComments()
  }, [])

  return (
    <>
      <DefaultLayout
        title={`${frontmatter.title} - ${siteConfig.title}`}
        description={frontmatter.description}
      >
        <main>
          <h1 className="page-title">{frontmatter.title}</h1>
          {isPost && (
            <div className="text-gray-500 text-sm italic">
              {frontmatter.dateFormatted}
            </div>
          )}
          <div>{children}</div>
          <section
            className="border-t border-border border-dashed mt-20 pt-5"
            ref={commentsSection}
          ></section>
        </main>
      </DefaultLayout>
    </>
  )
}

// src/layouts/page.vue
<script setup lang="ts">
import dayjs from 'dayjs'
import { siteConfig } from 'saber/config'
import { onMounted, ref, computed } from 'vue'
import TweetButton from '$src/components/TweetButton.vue'
import DefaultLayout from './default.vue'

const { page, Component } = defineProps({
  page: null,
  Component: null,
})

const isPost = page.type === 'post'

const commentsSection = ref<HTMLDivElement | null>(null)

onMounted(() => {
  const attrs = {
    repo: 'egoist/website',
    'issue-term': 'pathname',
    label: 'comment',
    theme: 'preferred-color-scheme',
    crossorigin: 'anonymous',
  }
  const script = document.createElement('script')
  script.src = `https://utteranc.es/client.js`
  script.async = true
  for (const key of Object.keys(attrs)) {
    script.setAttribute(key, attrs[key])
  }
  commentsSection.value.append(script)
})

const tweetText = computed(
  () => `Check out "${page.title}" by @${siteConfig.twitter}`
)
</script>

<template>
  <DefaultLayout
    :title="`${page.title} - ${siteConfig.title}`"
    :description="page.excerpt"
  >
    <main>
      <h1 class="page-title">{{ page.title }}</h1>
      <div v-if="isPost" class="text-gray-500 text-sm italic">
        {{ dayjs(page.createdAt).format('MMM DD, YYYY') }}
      </div>
      <div class="mt-5">
        <component :is="Component" />
        <div v-if="isPost" class="mt-10">
          <TweetButton
            :url="`${siteConfig.url}${page.permalink}`"
            :text="tweetText"
          />
        </div>
      </div>
      <section
        class="border-t border-border border-dashed mt-20 pt-5"
        ref="commentsSection"
      ></section>
    </main>
  </DefaultLayout>
</template>
